CREATE TABLE "user" (
    "id" SERIAL PRIMARY KEY,
    "username" VARCHAR (80) UNIQUE NOT NULL,
    "password" VARCHAR (1000) NOT NULL
);

CREATE TABLE "pairing" (
	id SERIAL PRIMARY KEY,
	"wine" VARCHAR (1000) NOT NULL,
	"food" VARCHAR (1000) NOT NULL,
	"description" VARCHAR(10000) NOT NULL
);

CREATE TABLE "saved_pairing" (
	id SERIAL PRIMARY KEY,
	"pairing_id" INT REFERENCES "pairing",
	"user_id" INT REFERENCES "user"
);

CREATE TABLE "user_insights" (
	id SERIAL PRIMARY KEY,
	"user_id" INT REFERENCES "user",
	"saved_pairing_id" INT REFERENCES "saved_pairing",
	"wine_drank" VARCHAR (200) NOT NULL,
	"thoughts" VARCHAR (10000) NOT NULL,
	"location" VARCHAR (200) NOT NULL,
	"enjoyed_with" VARCHAR (100),
	"image" VARCHAR (10000) NOT NULL
);

INSERT INTO pairing (food, wine, description) VALUES
('99-cent-pizza', 'Montepulciano d’’Abruzzo', 'Cheap slices always have plenty of red sauce tomato acid, and you want a wine with a good amount of acid, too, so it won’’t taste flat or strangely sweet in comparison to the pizza. The fatty mozzarella is even more reason to pick a crisp, sharp wine. Montepulciano, which is a grape grown all over Italy, is naturally wine in acidity and a dear friend to the budget slice. The vivid, plummy, medium-bodied red is notable for its aromatic herbs- oregano and pepper in particular - which seamlessly fill out the flavor deficits, namely blandness, that come with pizza that costs as much as breath savers. These wines are best server with a slight chill, so drop them in the fridge first!'),
('Grilled Cheese', 'Cahors', 'whether you’’re nine or ninety-nine, the soft, creamy, buttery-crisp, steaming-hot joy of grilled cheese is universal. And the bread-and-cheese sleeve of crunchy ooze is simple enough even for those who can’’t boil an egg to execute. A cheese sandwich of such immense staying power wants a red wine with generous reserves of supple tannin, fruity pop, and firm body to slice and dice the greasy starch and fatty dairy. The red wine is Malbec- not from Argentina but from southwestern France. In Cahors, the wines are distinct from the Southern Hemisphere versions you might know. Where the Argentine edition has a velvety texture that might whimper at the onslaught of melted lipids, Cahors has a bitter chew that eats through them like a wood chipper. These rustic wines have more tart in the form of dark fruits like plum and blackberry, and their tannins are taut as Simon Cowell’’s brow. Its a savory little package with grilled cheese that makes me buckle at the knees.'),
('Packaged Ramen', 'Alsace Pinot Gris', 'All ramen is dominated by rich, savory flavors. This kind of unbridled unami calls for a wine with both a touch of residual sweetness and a truckload of acidity to level the flavor. Alsatian Pinot Gris is often off-dry, which translates to "a little sweet," with a light sugar element that will temper the broth’’s saltiness by softening its intensity. Because you also need a wine with enough body and texture to avoid falling flat against the broth, Pinot Gris, with its glorious ability to sing a high, bright note while remaining grounded in richness and weight, is the ultimate ramen lover. With its easy texture, high acidity, and soft sweetness, it’’s positioned to get the most out of the many toppings you see in high-end ramen. It can manage all the fatty, savory, and bitter you throw at it, particularly all at once.'),
('Kentucky Fried Chicken', 'Brut Champagne', 'There is no bad time to drink Champagne. This is a universal truth that needs no undoing. The only question becomes: What do you want to eat with if? When Champages are made, they go through a process called autolysis, during which the wine spends time sur lie. This is a French phrase that is a much more beautiful way of saying the wine was aged on the dead yeast that’’s left over after fermentation ends. The liquid in each bottle eventually takes on the flavors of that yeast - it’’s the toasted brioche that comes through when you smell and taste good champagne. Those bread flavors also align with the golden goodness of fried chicken, and i’’m honor bound to stand behind the colonel’’s original recipe here. The secret spice blend is packed with savory, umami-driven pleasures, which along with the chicken grease call out for Champagnes natural acidity. The bubbles bring home the crunch of the skin and coating. As for the Champagne, look for brut multiple vintage(brut meaning dry, and multiple vintage, or MV, meaning a blend of grapes from different years, also known as Non-Vintage, or NV). This is the style every Champagne house hands its hat on, and because it makes up a majority of those houses production, it’’s easy to find.'),
('BBQ', 'Cote-Rotie', 'The rhone Valley is a diverse, dynamic region that stretches approximately 120 miles north to south and can be cut in half both geographically and stylistically.  The southern part makes wines that are based on the grape Grenache and can have a lot of other red and whites grapes blended in. But in the north, it’’s all about the magnificent red grape we call Syrah. Within the Northern Rhone, there are five smaller applications - each with its own distinct characteristics and idiosyncrasies - that use Syrah as their base. What makes Cote-Rotie such a unicorn among them is actually explained in its name. In English, it translates to "the roasted slope," because the steep inclines where the wines grow face south toward the Rhone River and get a lot of sunshine. That allows the grapes to ripen to their full and most powerfully tannic potential, and the resulting expression yields a robust set of aromas and flavors like olives, white pepper, bacon fat, and black fruits of all kinds, along with a distinct smokiness thats a dead ringer for charcoal. No matter what type of barbecue you love, these wines will get the very most out of every juicy, smoky hunk. The appellation is small and prestigious, so the wines start on the pricey side and only go up from there. but Cote-Rotie is so consistently good, you get what you pay for.'),
('Big Mac', 'Red Burgundy', 'One of the hallmarks of red Burgundy is its earthy, mushroomy flavor, which is slightly subtler in regional bottlings, where the wine’’s fruitier elements tend to take the main stage. Red Burgundies hit you first with a very distinct salvo of red cherry, followed by red hibiscus and raspberry. That very specific tang hitches a loud and proud ride on the Big Mac’’s special sauce, while the burgundys low hum of mushroom forms a backbeat with the sesame seed bun. It’’s gentle tannic kick clears away the fat of the beef and cheese, and the pickles enhance the Burgundys fruity autotune.'),
('Dark Chocolate Peanut Butter Cups', 'Oloroso Sherry', 'My best piece of advice is to lock them up or share them if you don’’t want to eat every single cup in one sitting. Beyond that, you’’e on your own with your willpower. With sherry, there are a number of styles that range from desert dry to sticky sweet. Some are fresh and smell like a bag of raw, unsalted almonds. Others are oxidized and packed with a nuttiness similar to the roasted candied nuts you get from street cars. Names like "fino" or "Oloroso" are telling you the style that’’s in the bottle. The lighter ones are usually consumed before dinner as an aperitif, while the oxidized styles go with dessert as a digestif.'),
('Thai and Vietnamese', 'German off-dry Riesling', 'Spicy foods like Thai and Vietnamese need lower alcohol so the wines don’’t aggravate that heat. Wines with more perfumed aromas also swell nicely around dishes with a lot of pungent ingredients in the same bite, from chiles and curry to lemongrass and mango. And you’’ll want enough acidity for all those supercharged contrasts in flavor and texture'),
('Red-Sauce Pasta', 'Piedmont Arneis or Tuscan Sangiovese', 'Arneis has an herbal gusto that allows fresh basil to sing, and Sangiovese has an unmistakable profile of tart cherry, red pepper, and ripe tomato that will leave you wondering, where the wine ends and the sauce begins. One of the most obvious examples of "what grows together goes together," red sauce and red fruit have been walking hand in hand since Roman times.'),
('Sushi', 'Gruner Veltliner', 'Soy and umami are behind much of Japanese cuisine, which can be fried or raw and everything in between. Sake is an obvious choice, but there are many great options if you stick with wines that are lighter in texture and body with more acidity and plenty of herbal and flinty savory notes.'),
('Shrimp Cocktail', 'Valdeorras Godello', 'With their combination of grapefruit lemon, along with a crush of acid and gravelly minerality, Valdeorras Godellos can be a near dead ringer for Sauvignon Blanc. What makes them distinct is that they have higher alcohol than your typical Sauvignon Blanc and a saline drag that begs for food - specifically the sea and finger kind. Shrimp cocktail obliges Spanish Godello in kind, with its mild ocean flavor and sharp cocktail-sauce tang. Both are invigorated by Godellos opulent, briny edge. And the cost of pairing with this mid-level white never gets jumbo, so you can always be the host with the most shrimp.');